# Credit to https://docs.platformio.org/en/latest/integration/ci/github-actions.html#using-cmd-run-command for this file

name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        pio update
    - name: Clean everything
      run: pio run --target clean
    - name: Run PlatformIO
      run: pio run     
    - name: Prepare for upload
      run: |
        rm "Copy to SD Card root directory to update/"*.bin
        cp .pio/build/BIGTREE_TFT35_E3_V3_0/BIGTREE_TFT35_V3.0_E3.26.x.bin "Copy to SD Card root directory to update/firmware.bin"
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Files for SD Card
        path: "Copy to SD Card root directory to update/"
